### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [vincentjames501/fish-kill-on-port#1]
I installed this plugin yet the command doesn't seem to exist. I'm new to fish/omf so I could be doing something wrong. I tried restarting fish but it still says command not found.

**Comment by vincentjames501** [comment]
Thanks. Looks like omf changed where the functions needed to be and how they were loaded. I also removed the dependency on getopts as it is suffering the same issue. Note the usage did change a bit which I updated in the README.
